### ISSUE TITLE
[Bug] [Mobile] Task timer halts when browser is minimized and when on different tab

### ISSUE THREAD

**Issue by LJMNZS** [cse112-sp22-group4/Electric-Pomato#61]
The task timer is frozen on the same time when the browser is on a different app, or when the browser is running in the background.
Only tested on Firefox Android, could do with testing on different browsers and mobile OS

**Comment by alanlwang1** [comment]
I tried checking for this bug on our current website and I couldn't reproduce it. Can you try to reproduce it as well?

**Comment by LJMNZS** [comment]
I tested and can't reproduce it either. Think this was fixed with Chris's timer changes. Closing.
